config/routes.rb
Rails.application.routes.draw do
  
  get 'checker/show'

  root 'checker#show'

end

app/models/checkcomp.rb
class Checkcomp < ActiveRecord::Base
  belongs_to :checklist
end

app/models/checklist.rb
class Checklist < ActiveRecord::Base
    has_many :checkcomps, dependent: :destroy
    accepts_nested_attributes_for :checkcomps, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/checker_controller.rb
class CheckerController < ApplicationController
  def show
    #@checklist = Checklist.new()
  end
  def checklist_param
    params.require(:checklist).permit(
      checkcomp_attributes: [:id, :checkerlist_id, :checked, :check_detail, :_destroy]
    )  
  end
end

app/controllers/checker_controller_.rb
class CheckerController < ApplicationController
    
    def show
    end
    
    def checklist_param
        params.require(:checklist).permit(
          checkcomp_attributes: [:id, :checkerlist_id, :checked, :check_detail, :_destroy]
        )  
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "忘れ物Checker" # 自分のアプリ名を設定する
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/checker_helper.rb
module CheckerHelper
end

app/views/checker/show.html.erb
<div class="container">
    
    <div class="row">
        <div class="col-sm-1 col-xs-1 col-md-1 col-lg-1 col-xl-1" style="text-align:center;">
            <input type="checkbox"/>
        </div>
        <div class="col-sm-8 col-xs-8 col-md-8 col-lg-8 col-xl-8">
            <input type="text" class="form-control"/>
        </div>
        <div class="col-sm-1 col-xs-1 col-md-1 col-lg-1 col-xl-1">
            <!-- 領域を確保するため、hiddenにて定義 -->
            <input type="button" class="btn btn-danger" style="visibility:hidden;"/>
        </div>
    </div>

        <%= nested_form_for(Checklist.new(), url: checker_show_path) do |c| %>
            <%= c.fields_for :checkcomps do |comp_form| %>
            <div class="row" style="margin-top:5px;margin-bottom:5px;">
                <div class="col-xs-1 col-md-1 col-lg-1 col-xl-1" style="text-align:center;">
                    <%= comp_form.check_box :checked %>
                </div>
                <div class="col-sm-8 col-xs-8 col-md-8 col-lg-8 col-xl-8">
                    <%= comp_form.text_field :detail ,class: 'form-control'%>
                </div>
                <div class="col-sm-1 col-xs-1 col-md-1 col-lg-1 col-xl-1">
                    <%= comp_form.link_to_remove "削除" ,class: 'btn btn-danger'%>
                </div>
            </div>
        <% end %>
        <%= c.link_to_add "追加", :checkcomps ,class: 'btn btn-primary',style: 'margin-top:15px'%>
        <% end %>
        
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width">
  <title>忘れ物Checker</title>
</head>

<body style="background-color: #FEF3DF;width: 100%;">
<header>
  <div class="jumbotron" style="background-color:#4DAB86">
    <h1 style="color:#FEF3DF"><i class="fa fa-pencil"></i> 忘れ物はありませんか？</h1>
    <!-- #3C4565 -->
  </div>
</header>
<%= yield %>

</body>
</html>